# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  austin-app:
    image: austin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://austin-postgresql:5432/austin
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://austin-postgresql:5432/austin
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9999:9999
  austin-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/jhipster/austin/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=austin
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
